using System;

namespace PLAgentDll
{
	public enum AgentEventType
	{
		AGENT_EVENT_Unknow,
		AGENT_EVENT_CALL,
		AGENT_EVENT_MSG,
		AGENT_EVEN_LOGOUT,
		AGENT_EVENT_STATUS,
		AGENT_EVENT_RESPONSE,
		AGENT_EVENT_EVENT,
		AGENT_EVENT_MYDEFINE
	}
}
