using System;

namespace PLAgentDll
{
	public enum EventQualifier
	{
		Unknow = 100,
		InitCall_NormalCall,
		DesBusy_NormalCall,
		Answered_NormalCall,
		CallOut_NormalCall,
		CallIn_NormalCall,
		HangUp_NormalCall,
		Disconnect_NormalCall,
		Bridge_NormalCall,
		SignIn_Ring_NormalCall,
		SignIn_Play_NormalCall,
		CallOut_Ring,
		Check_ExtenStatus,
		Hold_NormalCall,
		StopHold_NormalCall,
		Mute_NormalCall,
		StopMute_NormalCall,
		Consult_Call_In,
		Consult_Cancel_Result,
		Eavesdrop_Result,
		StopListen_NormalCall,
		Transfer_Blind_Agent_NormalCall,
		InterceptCall_NormalCall,
		Interrupt_NormalCall,
		ForceDisconnect_NormalCall,
		Internal_Call,
		Internal_Caller_Ring,
		Internal_Call_CallIn,
		Grade_NormalCall,
		Predict_CallOut_Bridge_Ring,
		Get_Access_Numbers,
		Three_Way_Call_Result,
		Three_Way_Call_In,
		Three_Way_Call_Cancel_Result,
		Consult_Call_Result,
		Consult_Transfer_Result,
		Whisper_Result,
		Bargein_Result,
		Force_Hangup_Result,
		Eavesdrop_Ring_Myself,
		Whisper_Ring_Myself,
		Bargein_Ring_Myself,
		Force_Hangup_Ring_Myself,
		Transfer_Queue_NormalCall,
		Transfer_IVR_NormalCall,
		Transfer_Blind_Call_In,
		Get_Online_Agents,
		Get_Ivr_List,
		Get_Queue_List,
		Manual_Callout,
		Get_Defined_Role_Rights,
		Get_Agent_Group_List,
		Get_Agents_Of_Queue,
		Get_Agents_Of_Agent_Group,
		Get_Agents_Monitor_Info,
		Get_Detail_Call_Info,
		Get_Customer_Of_Queue,
		Add_Customer_To_Queue = 158,
		Del_Customer_From_Queue,
		Update_Customer_Of_Queue,
		Consultee_Hangup_Call,
		Threewayee_Hangup_Call,
		Get_Website_Info,
		Get_Ivr_Profile_List,
		Transfer_IVR_Profile_NormalCall,
		Force_Change_Status_Result,
		Get_Queue_Statis,
		Get_Customer_Of_My_Queue,
		Callee_Answered,
		Get_Agent_Personal_info,
		Set_Agent_Personal_info,
		Change_Pswd,
		Get_Report_Statis_Info,
		Get_All_Queue_Statis,
		Apply_Change_Status,
		Apply_Change_Status_Distribute,
		Approve_Change_Status_Distribute,
		Get_Agentgroup_Status_Max_Num,
		Set_Agentgroup_Status_Max_Num,
		Approve_Change_Status_Result,
		Apply_or_Approve_Change_Status_Timeout_Distribute,
		Apply_Change_Status_Cancel,
		Apply_Change_Status_Cancel_Distribute,
		Get_Change_Status_Apply_List,
		HangUp_NormalCallResult,
		Record_Start,
		Record_Stop,
		Evaluate_Result_Event,
		Offline_Status = 200,
		Online_Status,
		Login_Status,
		LogOut_Status,
		SignIn_Status,
		SignOut_Status,
		Warn_Agent_Resignin,
		Warn_Agent_Force_Change_Status,
		Blind_Transfer_Outbound_Failed,
		Queue_Transfer_Outbound,
		Socket_Disconnect = 300,
		Socket_HeartBeat = 400,
		Sys_KickOut = 500,
		Sys_ResponseTimeOut,
		Sys_GetAgentDefineStatus,
		Sys_AgentStatusChange,
		Sys_ThrowException,
		Sys_AgentStatusChangeResult,
		Monitor_Agent = 600,
		Monitor_Queue
	}
}
